### ISSUE TITLE
Make `create_network` more verbose

### ISSUE THREAD

**Issue by drvinceknight** [CiwPython/Ciw#120]
Currently it just takes a generic `kwargs` which it passes to the `create_network_from_dictionary`, this would be more pythonic if it had a number of default arguments which could still be passed a dictionary (`**parameters`) but would allow for more feedback to user.

**Comment by geraintpalmer** [comment]
Thinking of removing `kwargs` altogether.

Have the following as `args`:

+ `Arrival_distributions`
+ `Baulking_functions`
+ `Class_change_matrices`
+ `Number_of_servers`
+ `Priority_classes`
+ `Queue_capacities`
+ `Service_distributions`
+ `Transition_matrices`

The only reason to also include `kwargs` is because of server schedules. This can be refactored so that server schedules are put into `Number_of_servers` directly.

**Comment by geraintpalmer** [comment]
Implemented in commit c699ec3b4c8c7e352181fc9f10d65a0be0fee46c
