### ISSUE TITLE
Arrival Schedules 

### ISSUE THREAD

**Issue by mnips** [CiwPython/Ciw#122]
Just Like Server Schedules, can we incorporate Arrival Schedules ( for example - Peak Hours at restaurant, traffic etc). We can do this by providing another attribute to params:-

```
Arrival Schedules : ['schedule']
schedule=[[Distribution-1,10],[Distribution-2,40],[Distribution-3,100]]
```

where 'Distribution-k' represents Arrival Distributions ,1<=k<=3
and 10,40,100 are the time till which that distribution is followed.
0-10 -Distribution-1
10-40 Distribution-2
40-100 Distribution-3

**Comment by geraintpalmer** [comment]
Hi @mnips thanks for the suggestion! I think this can be done with a `TimeDependent` arrival distribution:

```
def arrival_schedules(t):
    if t <= 10:
        return random.expovariate(0.4)
    if t < 40:
        return random.expovariate(0.2)
    if t < 100:
        return random.expovariate(0.3)
```

And then include this in the `Arrival_distributions`:

```
Arrival_distributions=[['TimeDependent`, arrival_schedules]]
```

More info on time dependent distributions here: http://ciw.readthedocs.io/en/latest/Guides/time_dependent.html

**Comment by mnips** [comment]
Doubt 1 - Related: If simulation is run for say 200(>100), does it cycle through. What happens in this case?
I know that for a fixed cycle we can use "mod" operator to work with it. 

Doubt 2: Are there any structural changes in v1.1.0 (overall)?

**Comment by geraintpalmer** [comment]
1) OK, if you intend for it to cycle you can use modulo arithmetic:

```
def arrival_schedules(t):
    if t % 100 <= 10:
        return random.expovariate(0.4)
    if t  % 100 < 40:
        return random.expovariate(0.2)
    if t % 100 < 100:
        return random.expovariate(0.3)
```

and since `t % 100` cannot be greater than 100, we have:

```
def arrival_schedules(t):
    if t % 100 <= 10:
        return random.expovariate(0.4)
    if t  % 100 < 40:
        return random.expovariate(0.2)
   return random.expovariate(0.3)
```

2) 2 changes occurred in version 1.1.0:

+ `ciw.create_network` is slightly refactored, no user facing changes however.

+ Input for server schedules have been refactored. We now define the schedule inside the `Number_of_servers` list, rather than give that a string, and define the schedule outside. The latest documentation is up to date with version 1.1.0 and will explain this change:
http://ciw.readthedocs.io/en/latest/Guides/server_schedule.html

I hope that helps!

**Comment by mnips** [comment]
Yes that's good. So should I keep this open as a suggestion or close it.

**Comment by drvinceknight** [comment]
> Yes that's good. So should I keep this open as a suggestion or close it.

I think it can be closed. :+1:  (It can always be reopened if need be.)
