### ISSUE TITLE
When creating a time dependent distribution why can't I return a function of t? 

### ISSUE THREAD

**Issue by Jped** [CiwPython/Ciw#146]
Hi I am trying to create a sinusoidal time dependent distribution.
However when I try to return the sin function the program freezes and the time does not increment.
Here is code for a distribution that works: 
```
def time_dependent_function(t):
     if (t%5)<2:
         print t
         s = round(abs(math.sin(t%6)),2)
         return 5.0
     else:
         return 4.0
```
Here is code for a distribution that freezes the simulation:  
(it just prints out a bunch of zeros and doesnt proceed) 
```
def time_dependent_function(t):
     if (t%5)<2:
         print t
         s = round(abs(math.sin(t%6)),2)
         return s
     else:
         return 4.0
```

**Comment by geraintpalmer** [comment]
Hi @Jped are you using this distribution for Arrivals or for Services?

**Comment by geraintpalmer** [comment]
If using for Arrival_distribution:

The first time to be sampled is `0` (as the simulation begins at `t=0` and `time_dependent_function(0)` is `0`).

If sampling a `0` for inter-arrival times the simulation will get stuck in an infinite loop:
At time `0` a customer arrives, then after `0` time units another customer arrives, then after `0` time units another customer arrives, and so on. Hence getting stuck in an infinite loop and the time not incrementing.

Could the function be adapted so that an inter-arrival time of `0` is not sampled?

**Comment by Jped** [comment]
Hi @geraintpalmer 
I see, that makes a lot of sense.
I just edited the code and it works now, thanks!
